@include('seller.layouts.adminHeader')
@include('seller.layouts.adminSidebar')
@include('seller.layouts.messages')
@include('seller.layouts.errors')
@yield('content')
@include('seller.layouts.adminFooter')
